.TH "Properties/AssemblyInfo.cs" 3 "Fri Mar 17 2017" "Network Control Module for Data Acquisition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Properties/AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Network Control Module for Data Acquisition from the source code\&.
