.TH "NetworkControlModule.Program" 3 "Fri Mar 17 2017" "Network Control Module for Data Acquisition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkControlModule.Program
.SH SYNOPSIS
.br
.PP
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "The main entry point for the application\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Program\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void NetworkControlModule\&.Program\&.Main ()\fC [static]\fP, \fC [private]\fP"

.PP
The main entry point for the application\&. 
.PP
Definition at line 14 of file Program\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Network Control Module for Data Acquisition from the source code\&.
