.TH "ProjectInstaller.cs" 3 "Fri Mar 17 2017" "Network Control Module for Data Acquisition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectInstaller.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNetworkControlModule\&.ProjectInstaller\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNetworkControlModule\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Network Control Module for Data Acquisition from the source code\&.
